@baseUrl = http://localhost:8080
### API docs
# Swagger UI: {{baseUrl}}/docs/
# OpenAPI JSON: {{baseUrl}}/openapi.json
### Root (HTML)
GET {{baseUrl}}/

###

### /api/hello
GET {{baseUrl}}/api/hello
Accept: application/json

###

### /api/test
GET {{baseUrl}}/api/test
Accept: application/json

###

### /api/time
GET {{baseUrl}}/api/time
Accept: application/json

###

### /api/error  (expect 500)
GET {{baseUrl}}/api/error

###

### /api/error401  (expect 401)
GET {{baseUrl}}/api/error401

###

### /api/error403  (expect 403)
GET {{baseUrl}}/api/error403

GET {{baseUrl}}/api/test
Accept: application/json

###

### /api/time
GET http://{{baseUrl}}/api/time
Accept: application/json

###

### /api/error  (expect 500)
GET http://{{baseUrl}}/api/error

###

### /api/error401  (expect 401)
GET http://{{baseUrl}}/api/error401

###

### Health endpoints (liveness/readiness/started)

### Get liveness (maps to is_ready)
GET {{baseUrl}}/liveness

### Set liveness to true
POST {{baseUrl}}/liveness/true

### Set liveness to false
POST {{baseUrl}}/liveness/false

### Get readiness (maps to is_live)
GET {{baseUrl}}/readiness

### Set readiness to true
POST {{baseUrl}}/readiness/true

### Set readiness to false
POST {{baseUrl}}/readiness/false

### Get started (maps to is_started)
GET {{baseUrl}}/started

### Set started to true
POST {{baseUrl}}/started/true

### Set started to false
POST {{baseUrl}}/started/false

### /api/error403  (expect 403)
GET http://{{baseUrl}}/api/error403